CREATE TABLE IF NOT EXISTS item(id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(80),
item_status VARCHAR(30) NOT NULL);

CREATE TABLE IF NOT EXISTS role (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30));

CREATE TABLE IF NOT EXISTS user(id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(70) UNIQUE,
password VARCHAR(255),
role_id BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (role_id) REFERENCES role (id));